openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "API Backend Donation UMKM"
  description: "Api specification for backend Donation UMKM"
  "contact" : 
    name : "Ahmad Zaky"
    email : "ahmadzaky@mhs.unsyiah.ac.id"
servers:
  - url: "https://localhost:9990/api/v1/"
    description: "API Gateway"
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"

  - url: "https://localhost:9991/api/v1/"
    description: "Service User Investore"
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod" 

  - url: "https://localhost:9992/api/v1/"
    description: "service user campaign"
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"

  - url: "https://localhost:9993/api/v1/"
    description: "service user reviewer"
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod" 
  
  - url: "https://localhost:9994/api/v1/"
    description: "Service detail & campaign "
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"

  - url: "https://localhost:9995/api/v1/"
    description: "Service transaction "
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"

  - url: "https://localhost:9996/api/v1/"
    description: "Service reviewer deatil "
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"
  
  - url: "https://localhost:9997/api/v1/"
    description: "Service return profit"
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"
  
  - url: "https://localhost:9998/api/v1/"
    description: "Service admin"
    variables: 
      environment: 
        default: "dev"
        description: "Server Enviroment"  
        enum :
          - "dev"
          - "qa"
          - "prod"

components:
  securitySchemes:
    # See https://demo.identityserver.io/ for configuration details.
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
security:
  - identity_server_auth:
    - api
    
# PATH Router
paths:
  /test/{test}:
    get:
      summary: "Runs a test request against the Identity Server demo API"
      tags:
        - test
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
      parameters: 
        - name: "include_done"
          description: "Include done todolist in the result"
          required: true
          in: "query"
          schema:
            type: "string"        

        - name: "include_all"
          description: "Include all todolist in the result"
          required: false
          in: "query"
          schema:
            type: "string" 
      

    post:
      summary: "Runs a test request against the Identity Server demo API"
      tags:
        - test
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"

        
  
  /test/hub:
    get:
      summary: Create a test
      operationId: createPets
      tags:
        - test
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error

  # create akun user investor
  /users_investore/register:
      post:
        tags:
          - "User Investore"
        summary: "RegisterUserInvestore"
        operationId: "registerUserInvetore"
        description: User Login
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error


  /users_investore/login:
      post:
        tags:
          - "User Investore"
        summary: "LoginUserInvestore"
        operationId: "loginUser"
        description: User Login
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error
  
  # create akun user Campaign 
  /users_campaign/register:
      post:
        tags:
          - "User Campaign"
        summary: "RegisterUserCampaign"
        operationId: "registerUserInvetore"
        description: User campaign Login
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error


  /users_campaign/login:
      post:
        tags:
          - "User Campaign"
        summary: "LoginUserCampaign"
        operationId: "loginUser"
        description: User Campaign Register
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error


# create akun user Campaign 
  /users_reviewer/register:
      post:
        tags:
          - "User reviewer"
        summary: "RegisterUserreviewer"
        operationId: "registerUserInvetore"
        description: User reviewer Login
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error


  /users_reviewer/login:
      post:
        tags:
          - "User reviewer"
        summary: "LoginUserreviewer"
        operationId: "loginUserReviewer"
        description: User reviewer Register
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error

# create Campaign detail
  /campaign_detail:
      post:
        tags:
          - "Campaign Detail"
        summary: "Campaign Detail"
        operationId: "campaignDetail"
        description: Create Campaign for user Campaign
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error

# create Campaign images
  /campaign_images:
      post:
        tags:
          - "Campaign images"
        summary: "Campaign images"
        operationId: "campaignImages"
        description: Create Campaign images for campaign details
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error

# create reviewer detail
  /reviewer detail:
      post:
        tags:
          - "reviewer detail"
        summary: "Reviewer Detail"
        operationId: "reviewerDetail"
        description: Create reviewer for aprove campaign form campaign detail
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error

# create transaction
  /transaction:
      post:
        tags:
          - "Transaction"
        summary: "Transaction to backend"
        operationId: "transaction"
        description: Create transaction from user investor to campaign detail
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error

# create retutn profit
  /return_profit:
      post:
        tags:
          - "Return Profit"
        summary: "Return profit to user"
        operationId: "returnProfit"
        description: Create profit to user investor and user reviewer
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error

# create transaction
  /admin_on:
      post:
        tags:
          - "ADMIN"
        summary: "Admin create"
        operationId: "admin"
        description: Create admin for accsess all data and db 
        responses:
          "201":
            description: Null response
          default:
            description: unexpected error